services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        deploy:
            replicas: 10
    
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - 3000:3000

